// Let goreportcard check us.
// Code generated by gen_version; DO NOT EDIT.

//go:generate go run ./internal/gen/version

package csharg

// SemVersion is the semantic version string of the csharg module.
const SemVersion = "0.12.2-10-g6c9c830"
